<a href="https://colab.research.google.com/github/AbdulxoliqMirzayev/Malumotlarga-Ishlov-berish/blob/main/4_lesson.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('https://raw.githubusercontent.com/anvarnarz/praktikum_datasets/main/world_population_duplicates.csv', usecols=['country','pop2021','area'], index_col='country')
df.head()

           pop2021   area
country
Macau      658.394     30
Monaco      39.511      2
Burundi  12255.433  27834
Macau      658.394     30
Monaco      39.511      2

In [5]:
df.loc['Uzbekistan']

pop2021     33935.763
area       447400.000
Name: Uzbekistan, dtype: float64

In [6]:
df.loc['India']

pop2021    1393409.038
area       3287590.000
Name: India, dtype: float64

In [7]:
bins = [0,1000,10000,30000,50000,100000,300000,1500000]

In [8]:
population = df.pop2021

In [9]:
population

country
Macau                 658.394
Monaco                 39.511
Burundi             12255.433
Macau                 658.394
Monaco                 39.511
                      ...
Namibia              2587.344
Western Sahara        611.875
Mongolia             3329.289
Falkland Islands        3.533
Greenland              56.877
Name: pop2021, Length: 247, dtype: float64

In [10]:
guruh = pd.cut(population, bins)
guruh

country
Macau                    (0, 1000]
Monaco                   (0, 1000]
Burundi             (10000, 30000]
Macau                    (0, 1000]
Monaco                   (0, 1000]
                         ...
Namibia              (1000, 10000]
Western Sahara           (0, 1000]
Mongolia             (1000, 10000]
Falkland Islands         (0, 1000]
Greenland                (0, 1000]
Name: pop2021, Length: 247, dtype: category
Categories (7, interval[int64, right]): [(0, 1000] < (1000, 10000] < (10000, 30000] <
                                         (30000, 50000] < (50000, 100000] < (100000, 300000] <
                                         (300000, 1500000]]

In [11]:
guruh.value_counts()

pop2021
(0, 1000]            80
(1000, 10000]        73
(10000, 30000]       46
(30000, 50000]       19
(50000, 100000]      15
(100000, 300000]     11
(300000, 1500000]     3
Name: count, dtype: int64

In [12]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)

In [13]:
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [15]:
df.price.describe()

count       58.000000
mean     15387.000000
std      11320.259841
min       5151.000000
25%       6808.500000
50%      11095.000000
75%      18120.500000
max      45400.000000
Name: price, dtype: float64

In [16]:
bins = [0,10000,20000,50000]

In [17]:
range = pd.cut(df.price, bins)
range

index
0     (10000, 20000]
1     (10000, 20000]
2     (10000, 20000]
3     (10000, 20000]
4     (10000, 20000]
           ...
81        (0, 10000]
82        (0, 10000]
86        (0, 10000]
87    (10000, 20000]
88    (10000, 20000]
Name: price, Length: 61, dtype: category
Categories (3, interval[int64, right]): [(0, 10000] < (10000, 20000] < (20000, 50000]]

In [18]:
range.value_counts()

price
(0, 10000]        28
(10000, 20000]    17
(20000, 50000]    13
Name: count, dtype: int64

In [20]:
names = ["arzon", "o'rta","qimmat"]
range = pd.cut(df.price, bins, labels=names)
range.value_counts()

price
arzon     28
o'rta     17
qimmat    13
Name: count, dtype: int64

In [22]:
range = pd.cut(df.price, 5)
range.value_counts()

price
(5110.751, 13200.8]    32
(13200.8, 21250.6]     14
(29300.4, 37350.2]      7
(37350.2, 45400.0]      3
(21250.6, 29300.4]      2
Name: count, dtype: int64

In [23]:
range = pd.qcut(df.horsepower, 3)
range.value_counts()

horsepower
(47.999, 70.0]    24
(111.0, 288.0]    20
(70.0, 111.0]     17
Name: count, dtype: int64

In [24]:
df = pd.read_csv("https://github.com/anvarnarz/praktikum_datasets/raw/main/automobile_data.csv", index_col=0)

In [25]:
df.head()

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0

In [27]:
df.company.value_counts()

company
toyota           7
bmw              6
mazda            5
nissan           5
audi             4
mercedes-benz    4
mitsubishi       4
volkswagen       4
alfa-romero      3
chevrolet        3
honda            3
isuzu            3
jaguar           3
porsche          3
dodge            2
volvo            2
Name: count, dtype: int64

In [35]:
df.groupby(['company', 'body-style']).price.mean()

company        body-style
alfa-romero    convertible    14997.500000
               hatchback      16500.000000
audi           sedan          15550.000000
               wagon          18920.000000
bmw            sedan          27213.333333
chevrolet      hatchback       5723.000000
               sedan           6575.000000
dodge          hatchback       6303.000000
honda          sedan          11645.000000
               wagon           7295.000000
isuzu          sedan           6785.000000
jaguar         sedan          34600.000000
mazda          hatchback       7482.500000
               sedan          18344.000000
mercedes-benz  hardtop        45400.000000
               sedan          33256.000000
               wagon          28248.000000
mitsubishi     hatchback       5789.000000
               sedan           7589.000000
nissan         sedan           8524.000000
               wagon           7349.000000
porsche        convertible    37028.000000
               hardtop        34028.000000
               hatchback               NaN
toyota         hatchback       6058.000000
               wagon           9836.000000
volkswagen     sedan           8435.000000
volvo          sedan          12940.000000
               wagon          13415.000000
Name: price, dtype: float64

In [45]:
df.groupby('company').price.agg([min,max, lambda x : np.median(x)])

                   min      max  <lambda_0>
company
alfa-romero    13495.0  16500.0     16500.0
audi           13950.0  18920.0     16350.0
bmw            16430.0  41315.0     25865.0
chevrolet       5151.0   6575.0      6295.0
dodge           6229.0   6377.0      6303.0
honda           7295.0  12945.0     10345.0
isuzu           6785.0   6785.0         NaN
jaguar         32250.0  36000.0     35550.0
mazda           5195.0  18344.0      6795.0
mercedes-benz  25552.0  45400.0     34604.0
mitsubishi      5389.0   8189.0      6589.0
nissan          6649.0  13499.0      7099.0
porsche        34028.0  37028.0         NaN
toyota          5348.0  15750.0      6918.0
volkswagen      7775.0   9995.0      7985.0
volvo          12940.0  13415.0     13177.5